    name: SimpleServerManage
    main: me.axxonyara.minecraft.bukkit.plugins.simpleservermanage.SimpleServerManage
    version: 1.0
    softdepend: [Vault]
    commands:
       shutdown:
          description: This command will shut down your server, with an optional count down.
          usage: /shutdown [seconds to count]
          permission: simpleservermanage.shutdown
          permission-message: You don't have <permission>
       restart:
          description: This command will SHUT DOWN your server, but says that it will restart in the chat. It has an optional count down.
          usage: /restart [seconds to count]
          permission: simpleservermanage.restart
          permission-message: You don't have permission!